/**
 * Standardized Error Codes for HushRyd API
 * 
 * Industry Standard Numeric Error Codes:
 * - 1xxx: Authentication & Authorization
 * - 2xxx: Validation Errors
 * - 3xxx: Resource Not Found
 * - 4xxx: Business Logic Errors
 * - 5xxx: Payment & Wallet Errors
 * - 6xxx: External Service Errors
 * - 7xxx: Rate Limiting & Quota
 * - 8xxx: Configuration Errors
 * - 9xxx: Internal Server Errors
 */

export enum ErrorCode {
  // ==================== AUTHENTICATION & AUTHORIZATION (1000-1999) ====================
  AUTH_TOKEN_REQUIRED = 1001,
  AUTH_TOKEN_INVALID = 1002,
  AUTH_TOKEN_EXPIRED = 1003,
  AUTH_REFRESH_TOKEN_INVALID = 1004,
  AUTH_REFRESH_TOKEN_EXPIRED = 1005,
  AUTH_UNAUTHORIZED = 1006,
  AUTH_FORBIDDEN = 1007,
  AUTH_INVALID_CREDENTIALS = 1008,
  AUTH_OTP_INVALID = 1009,
  AUTH_OTP_EXPIRED = 1010,
  AUTH_OTP_NOT_SENT = 1011,
  AUTH_USER_NOT_FOUND = 1012,
  AUTH_USER_INACTIVE = 1013,
  AUTH_ROLE_INVALID = 1014,
  AUTH_SESSION_EXPIRED = 1015,
  AUTH_ACCOUNT_LOCKED = 1016,

  // ==================== VALIDATION ERRORS (2000-2999) ====================
  VALIDATION_REQUIRED = 2001,
  VALIDATION_INVALID_FORMAT = 2002,
  VALIDATION_INVALID_TYPE = 2003,
  VALIDATION_INVALID_LENGTH = 2004,
  VALIDATION_INVALID_RANGE = 2005,
  VALIDATION_INVALID_EMAIL = 2006,
  VALIDATION_INVALID_MOBILE = 2007,
  VALIDATION_INVALID_DATE = 2008,
  VALIDATION_INVALID_COORDINATES = 2009,
  VALIDATION_INVALID_AMOUNT = 2010,
  VALIDATION_INVALID_RATING = 2011,
  VALIDATION_INVALID_STATUS = 2012,
  VALIDATION_INVALID_FILE = 2013,
  VALIDATION_FILE_TOO_LARGE = 2014,
  VALIDATION_INVALID_FILE_TYPE = 2015,
  VALIDATION_MISSING_FIELD = 2016,
  VALIDATION_INVALID_ENUM = 2017,
  VALIDATION_INVALID_URL = 2018,
  VALIDATION_INVALID_PHONE_FORMAT = 2019,

  // ==================== RESOURCE NOT FOUND (3000-3099) ====================
  USER_NOT_FOUND = 3001,
  CUSTOMER_NOT_FOUND = 3002,
  DRIVER_NOT_FOUND = 3003,
  RIDE_NOT_FOUND = 3004,
  BOOKING_NOT_FOUND = 3005,
  VEHICLE_NOT_FOUND = 3006,
  ADDRESS_NOT_FOUND = 3007,
  PAYMENT_NOT_FOUND = 3008,
  WALLET_TRANSACTION_NOT_FOUND = 3009,
  REFERRAL_NOT_FOUND = 3010,
  SOS_ALERT_NOT_FOUND = 3011,
  RATING_NOT_FOUND = 3012,
  COMPLAINT_NOT_FOUND = 3013,
  SUPPORT_TICKET_NOT_FOUND = 3014,
  EMERGENCY_CONTACT_NOT_FOUND = 3015,
  PAYOUT_NOT_FOUND = 3016,
  KYC_DOCUMENT_NOT_FOUND = 3017,
  INVOICE_NOT_FOUND = 3018,

  // ==================== BUSINESS LOGIC ERRORS (4000-4999) ====================
  // User & Profile (4000-4049)
  USER_ALREADY_EXISTS = 4001,
  USER_PROFILE_INCOMPLETE = 4002,
  USER_PHONE_NOT_VERIFIED = 4003,
  USER_EMAIL_NOT_VERIFIED = 4004,
  USER_ALREADY_ACTIVE = 4005,
  USER_ALREADY_INACTIVE = 4006,
  USER_INVALID_ROLE = 4007,

  // Customer (4050-4099)
  CUSTOMER_INSUFFICIENT_WALLET_BALANCE = 4050,
  CUSTOMER_MAX_ADDRESSES_REACHED = 4051,
  CUSTOMER_ADDRESS_LABEL_EXISTS = 4052,
  CUSTOMER_MAX_BOOKINGS_REACHED = 4053,

  // Driver (4100-4149)
  DRIVER_KYC_PENDING = 4100,
  DRIVER_KYC_REJECTED = 4101,
  DRIVER_KYC_NOT_SUBMITTED = 4102,
  DRIVER_KYC_ALREADY_APPROVED = 4103,
  DRIVER_NO_VEHICLE = 4104,
  DRIVER_VEHICLE_NOT_ACTIVE = 4105,
  DRIVER_MAX_VEHICLES_REACHED = 4106,
  DRIVER_NOT_AUTHORIZED = 4107,
  DRIVER_BANK_DETAILS_MISSING = 4108,
  DRIVER_ALREADY_ON_RIDE = 4109,

  // Ride (4150-4199)
  RIDE_NOT_AVAILABLE = 4150,
  RIDE_ALREADY_STARTED = 4151,
  RIDE_ALREADY_COMPLETED = 4152,
  RIDE_ALREADY_CANCELLED = 4153,
  RIDE_CANNOT_CANCEL = 4154,
  RIDE_INVALID_TIME = 4155,
  RIDE_INVALID_LOCATION = 4156,
  RIDE_INVALID_DISTANCE = 4157,
  RIDE_INVALID_PRICE = 4158,
  RIDE_SEATS_UNAVAILABLE = 4159,
  RIDE_NOT_ACTIVE = 4160,
  RIDE_LOCATION_STATE_INVALID = 4161,
  RIDE_HAS_CONFIRMED_BOOKINGS = 4162,

  // Booking (4200-4249)
  BOOKING_NOT_AUTHORIZED = 4200,
  BOOKING_ALREADY_CONFIRMED = 4201,
  BOOKING_ALREADY_STARTED = 4202,
  BOOKING_ALREADY_COMPLETED = 4203,
  BOOKING_ALREADY_CANCELLED = 4204,
  BOOKING_CANNOT_CANCEL = 4205,
  BOOKING_PAYMENT_REQUIRED = 4206,
  BOOKING_PAYMENT_ALREADY_PROCESSED = 4207,
  BOOKING_INVALID_PASSENGER_COUNT = 4208,
  BOOKING_INVALID_OTP = 4209,
  BOOKING_INVALID_PIN = 4210,
  BOOKING_PICKUP_NOT_VERIFIED = 4211,
  BOOKING_DROP_NOT_VERIFIED = 4212,
  BOOKING_SEATS_UNAVAILABLE = 4213,
  BOOKING_CANNOT_START = 4214,

  // Address (4250-4279)
  ADDRESS_LABEL_INVALID = 4250,
  ADDRESS_LABEL_EXISTS = 4251,
  ADDRESS_MAX_REACHED = 4252,
  ADDRESS_COORDINATES_REQUIRED = 4253,

  // Rating (4280-4299)
  RATING_INVALID_VALUE = 4280,
  RATING_ALREADY_SUBMITTED = 4281,
  RATING_BOOKING_NOT_COMPLETED = 4282,
  RATING_NOT_AUTHORIZED = 4283,

  // Complaint (4300-4319)
  COMPLAINT_NOT_AUTHORIZED = 4300,
  COMPLAINT_INVALID_STATUS = 4301,
  COMPLAINT_SUBJECT_REQUIRED = 4302,
  COMPLAINT_DESCRIPTION_REQUIRED = 4303,

  // Support (4320-4339)
  SUPPORT_TICKET_NOT_AUTHORIZED = 4320,
  SUPPORT_TICKET_INVALID_STATUS = 4321,
  SUPPORT_TICKET_INVALID_PRIORITY = 4322,
  SUPPORT_TICKET_SUBJECT_REQUIRED = 4323,
  SUPPORT_TICKET_DESCRIPTION_REQUIRED = 4324,

  // Emergency Contact (4340-4359)
  EMERGENCY_CONTACT_NOT_AUTHORIZED = 4340,
  EMERGENCY_CONTACT_ALREADY_EXISTS = 4341,
  EMERGENCY_CONTACT_INVALID_MOBILE = 4342,
  EMERGENCY_CONTACT_NAME_REQUIRED = 4343,

  // Referral (4360-4379)
  REFERRAL_CODE_INVALID = 4360,
  REFERRAL_CODE_EXPIRED = 4361,
  REFERRAL_CODE_ALREADY_USED = 4362,
  REFERRAL_NOT_ELIGIBLE = 4363,

  // KYC (4380-4399)
  KYC_DOCUMENT_MISSING = 4380,
  KYC_DOCUMENT_INVALID = 4381,
  KYC_AADHAR_INVALID = 4382,
  KYC_PAN_INVALID = 4383,
  KYC_LICENSE_INVALID = 4384,
  KYC_LICENSE_EXPIRED = 4385,
  KYC_IFSC_INVALID = 4386,
  KYC_BANK_DETAILS_INCOMPLETE = 4387,
  KYC_SELFIE_REQUIRED = 4388,
  KYC_ALREADY_SUBMITTED = 4389,

  // Admin (4400-4449)
  ADMIN_ONLY = 4400,
  ADMIN_USER_NOT_FOUND = 4401,
  ADMIN_INVALID_ACTION = 4402,
  ADMIN_KYC_ALREADY_PROCESSED = 4403,
  ADMIN_INVALID_STATUS = 4404,
  ADMIN_INVALID_SETTINGS = 4405,

  // Driver Earnings (4450-4469)
  EARNINGS_INSUFFICIENT_BALANCE = 4450,
  EARNINGS_PAYOUT_PENDING = 4451,
  EARNINGS_PAYOUT_FAILED = 4452,
  EARNINGS_INVALID_AMOUNT = 4453,
  EARNINGS_BANK_DETAILS_REQUIRED = 4454,

  // ==================== PAYMENT & WALLET ERRORS (5000-5099) ====================
  PAYMENT_INVALID_AMOUNT = 5001,
  PAYMENT_INVALID_TRANSACTION = 5002,
  PAYMENT_ALREADY_PROCESSED = 5003,
  PAYMENT_FAILED = 5004,
  PAYMENT_CANCELLED = 5005,
  PAYMENT_INVALID_HASH = 5006,
  PAYMENT_GATEWAY_ERROR = 5007,
  PAYMENT_INSUFFICIENT_BALANCE = 5008,
  PAYMENT_REFUND_FAILED = 5009,
  PAYMENT_METHOD_INVALID = 5010,
  PAYMENT_TIMEOUT = 5011,
  PAYMENT_DECLINED = 5012,

  WALLET_INSUFFICIENT_BALANCE = 5050,
  WALLET_INVALID_AMOUNT = 5051,
  WALLET_TRANSACTION_EXPIRED = 5052,
  WALLET_TRANSACTION_INVALID = 5053,
  WALLET_MINIMUM_BALANCE = 5054,

  // ==================== UPLOAD & FILE ERRORS (6000-6099) ====================
  UPLOAD_FILE_REQUIRED = 6001,
  UPLOAD_FILE_TOO_LARGE = 6002,
  UPLOAD_INVALID_FILE_TYPE = 6003,
  UPLOAD_FAILED = 6004,
  UPLOAD_S3_ERROR = 6005,
  UPLOAD_AWS_CREDENTIALS_MISSING = 6006,
  UPLOAD_BASE64_INVALID = 6007,
  UPLOAD_STORAGE_QUOTA_EXCEEDED = 6008,
  UPLOAD_FILE_CORRUPTED = 6009,

  // ==================== EXTERNAL SERVICE ERRORS (6100-6199) ====================
  EXTERNAL_SERVICE_UNAVAILABLE = 6100,
  EXTERNAL_SERVICE_TIMEOUT = 6101,
  EXTERNAL_SERVICE_ERROR = 6102,
  SMS_SERVICE_ERROR = 6103,
  EMAIL_SERVICE_ERROR = 6104,
  PAYMENT_GATEWAY_UNAVAILABLE = 6105,
  MAP_SERVICE_ERROR = 6106,
  NOTIFICATION_SERVICE_ERROR = 6107,

  // ==================== RATE LIMITING & QUOTA (7000-7099) ====================
  RATE_LIMIT_EXCEEDED = 7001,
  QUOTA_EXCEEDED = 7002,
  TOO_MANY_REQUESTS = 7003,
  DAILY_LIMIT_EXCEEDED = 7004,
  HOURLY_LIMIT_EXCEEDED = 7005,

  // ==================== CONFIGURATION ERRORS (8000-8099) ====================
  CONFIG_MISSING = 8001,
  CONFIG_INVALID = 8002,
  FEATURE_DISABLED = 8003,
  MAINTENANCE_MODE = 8004,

  // ==================== INTERNAL SERVER ERRORS (9000-9999) ====================
  INTERNAL_SERVER_ERROR = 9001,
  DATABASE_ERROR = 9002,
  DATABASE_CONNECTION_ERROR = 9003,
  DATABASE_QUERY_ERROR = 9004,
  DATABASE_TRANSACTION_ERROR = 9005,
  CACHE_ERROR = 9006,
  NOT_IMPLEMENTED = 9007,
  SERVICE_UNAVAILABLE = 9008,
  UNKNOWN_ERROR = 9999,
}

/**
 * Error code to HTTP status code mapping
 */
export const ErrorStatusMap: Record<ErrorCode, number> = {
  // Auth errors - 401/403
  [ErrorCode.AUTH_TOKEN_REQUIRED]: 401,
  [ErrorCode.AUTH_TOKEN_INVALID]: 401,
  [ErrorCode.AUTH_TOKEN_EXPIRED]: 401,
  [ErrorCode.AUTH_REFRESH_TOKEN_INVALID]: 401,
  [ErrorCode.AUTH_REFRESH_TOKEN_EXPIRED]: 401,
  [ErrorCode.AUTH_UNAUTHORIZED]: 401,
  [ErrorCode.AUTH_FORBIDDEN]: 403,
  [ErrorCode.AUTH_INVALID_CREDENTIALS]: 401,
  [ErrorCode.AUTH_OTP_INVALID]: 400, // Bad Request - Invalid OTP input
  [ErrorCode.AUTH_OTP_EXPIRED]: 400, // Bad Request - Expired OTP
  [ErrorCode.AUTH_OTP_NOT_SENT]: 400,
  [ErrorCode.AUTH_USER_NOT_FOUND]: 404,
  [ErrorCode.AUTH_USER_INACTIVE]: 403,
  [ErrorCode.AUTH_ROLE_INVALID]: 400,
  [ErrorCode.AUTH_SESSION_EXPIRED]: 401,
  [ErrorCode.AUTH_ACCOUNT_LOCKED]: 403,

  // Validation errors - 400
  [ErrorCode.VALIDATION_REQUIRED]: 400,
  [ErrorCode.VALIDATION_INVALID_FORMAT]: 400,
  [ErrorCode.VALIDATION_INVALID_TYPE]: 400,
  [ErrorCode.VALIDATION_INVALID_LENGTH]: 400,
  [ErrorCode.VALIDATION_INVALID_RANGE]: 400,
  [ErrorCode.VALIDATION_INVALID_EMAIL]: 400,
  [ErrorCode.VALIDATION_INVALID_MOBILE]: 400,
  [ErrorCode.VALIDATION_INVALID_DATE]: 400,
  [ErrorCode.VALIDATION_INVALID_COORDINATES]: 400,
  [ErrorCode.VALIDATION_INVALID_AMOUNT]: 400,
  [ErrorCode.VALIDATION_INVALID_RATING]: 400,
  [ErrorCode.VALIDATION_INVALID_STATUS]: 400,
  [ErrorCode.VALIDATION_INVALID_FILE]: 400,
  [ErrorCode.VALIDATION_FILE_TOO_LARGE]: 400,
  [ErrorCode.VALIDATION_INVALID_FILE_TYPE]: 400,
  [ErrorCode.VALIDATION_MISSING_FIELD]: 400,
  [ErrorCode.VALIDATION_INVALID_ENUM]: 400,
  [ErrorCode.VALIDATION_INVALID_URL]: 400,
  [ErrorCode.VALIDATION_INVALID_PHONE_FORMAT]: 400,

  // Not Found errors - 404
  [ErrorCode.USER_NOT_FOUND]: 404,
  [ErrorCode.CUSTOMER_NOT_FOUND]: 404,
  [ErrorCode.DRIVER_NOT_FOUND]: 404,
  [ErrorCode.RIDE_NOT_FOUND]: 404,
  [ErrorCode.BOOKING_NOT_FOUND]: 404,
  [ErrorCode.VEHICLE_NOT_FOUND]: 404,
  [ErrorCode.ADDRESS_NOT_FOUND]: 404,
  [ErrorCode.PAYMENT_NOT_FOUND]: 404,
  [ErrorCode.WALLET_TRANSACTION_NOT_FOUND]: 404,
  [ErrorCode.REFERRAL_NOT_FOUND]: 404,
  [ErrorCode.SOS_ALERT_NOT_FOUND]: 404,
  [ErrorCode.RATING_NOT_FOUND]: 404,
  [ErrorCode.COMPLAINT_NOT_FOUND]: 404,
  [ErrorCode.SUPPORT_TICKET_NOT_FOUND]: 404,
  [ErrorCode.EMERGENCY_CONTACT_NOT_FOUND]: 404,
  [ErrorCode.PAYOUT_NOT_FOUND]: 404,
  [ErrorCode.KYC_DOCUMENT_NOT_FOUND]: 404,
  [ErrorCode.INVOICE_NOT_FOUND]: 404,

  // Business logic errors - 400/409
  [ErrorCode.USER_ALREADY_EXISTS]: 409,
  [ErrorCode.USER_PROFILE_INCOMPLETE]: 400,
  [ErrorCode.USER_PHONE_NOT_VERIFIED]: 400,
  [ErrorCode.USER_EMAIL_NOT_VERIFIED]: 400,
  [ErrorCode.USER_ALREADY_ACTIVE]: 400,
  [ErrorCode.USER_ALREADY_INACTIVE]: 400,
  [ErrorCode.USER_INVALID_ROLE]: 400,
  [ErrorCode.CUSTOMER_INSUFFICIENT_WALLET_BALANCE]: 400,
  [ErrorCode.CUSTOMER_MAX_ADDRESSES_REACHED]: 400,
  [ErrorCode.CUSTOMER_ADDRESS_LABEL_EXISTS]: 409,
  [ErrorCode.CUSTOMER_MAX_BOOKINGS_REACHED]: 400,
  [ErrorCode.DRIVER_KYC_PENDING]: 403,
  [ErrorCode.DRIVER_KYC_REJECTED]: 403,
  [ErrorCode.DRIVER_KYC_NOT_SUBMITTED]: 403,
  [ErrorCode.DRIVER_KYC_ALREADY_APPROVED]: 400,
  [ErrorCode.DRIVER_NO_VEHICLE]: 400,
  [ErrorCode.DRIVER_VEHICLE_NOT_ACTIVE]: 400,
  [ErrorCode.DRIVER_MAX_VEHICLES_REACHED]: 400,
  [ErrorCode.DRIVER_NOT_AUTHORIZED]: 403,
  [ErrorCode.DRIVER_BANK_DETAILS_MISSING]: 400,
  [ErrorCode.DRIVER_ALREADY_ON_RIDE]: 400,
  [ErrorCode.RIDE_NOT_AVAILABLE]: 400,
  [ErrorCode.RIDE_ALREADY_STARTED]: 400,
  [ErrorCode.RIDE_ALREADY_COMPLETED]: 400,
  [ErrorCode.RIDE_ALREADY_CANCELLED]: 400,
  [ErrorCode.RIDE_CANNOT_CANCEL]: 400,
  [ErrorCode.RIDE_INVALID_TIME]: 400,
  [ErrorCode.RIDE_INVALID_LOCATION]: 400,
  [ErrorCode.RIDE_INVALID_DISTANCE]: 400,
  [ErrorCode.RIDE_INVALID_PRICE]: 400,
  [ErrorCode.RIDE_SEATS_UNAVAILABLE]: 400,
  [ErrorCode.RIDE_NOT_ACTIVE]: 400,
  [ErrorCode.RIDE_LOCATION_STATE_INVALID]: 400,
  [ErrorCode.RIDE_HAS_CONFIRMED_BOOKINGS]: 400,
  [ErrorCode.BOOKING_NOT_AUTHORIZED]: 403,
  [ErrorCode.BOOKING_ALREADY_CONFIRMED]: 400,
  [ErrorCode.BOOKING_ALREADY_STARTED]: 400,
  [ErrorCode.BOOKING_ALREADY_COMPLETED]: 400,
  [ErrorCode.BOOKING_ALREADY_CANCELLED]: 400,
  [ErrorCode.BOOKING_CANNOT_CANCEL]: 400,
  [ErrorCode.BOOKING_PAYMENT_REQUIRED]: 400,
  [ErrorCode.BOOKING_PAYMENT_ALREADY_PROCESSED]: 400,
  [ErrorCode.BOOKING_INVALID_PASSENGER_COUNT]: 400,
  [ErrorCode.BOOKING_INVALID_OTP]: 400, // Bad Request - Invalid pickup OTP
  [ErrorCode.BOOKING_INVALID_PIN]: 400, // Bad Request - Invalid drop PIN
  [ErrorCode.BOOKING_PICKUP_NOT_VERIFIED]: 400,
  [ErrorCode.BOOKING_DROP_NOT_VERIFIED]: 400,
  [ErrorCode.BOOKING_SEATS_UNAVAILABLE]: 400,
  [ErrorCode.BOOKING_CANNOT_START]: 400,
  [ErrorCode.ADDRESS_LABEL_INVALID]: 400,
  [ErrorCode.ADDRESS_LABEL_EXISTS]: 409,
  [ErrorCode.ADDRESS_MAX_REACHED]: 400,
  [ErrorCode.ADDRESS_COORDINATES_REQUIRED]: 400,
  [ErrorCode.RATING_INVALID_VALUE]: 400,
  [ErrorCode.RATING_ALREADY_SUBMITTED]: 400,
  [ErrorCode.RATING_BOOKING_NOT_COMPLETED]: 400,
  [ErrorCode.RATING_NOT_AUTHORIZED]: 403,
  [ErrorCode.COMPLAINT_NOT_AUTHORIZED]: 403,
  [ErrorCode.COMPLAINT_INVALID_STATUS]: 400,
  [ErrorCode.COMPLAINT_SUBJECT_REQUIRED]: 400,
  [ErrorCode.COMPLAINT_DESCRIPTION_REQUIRED]: 400,
  [ErrorCode.SUPPORT_TICKET_NOT_AUTHORIZED]: 403,
  [ErrorCode.SUPPORT_TICKET_INVALID_STATUS]: 400,
  [ErrorCode.SUPPORT_TICKET_INVALID_PRIORITY]: 400,
  [ErrorCode.SUPPORT_TICKET_SUBJECT_REQUIRED]: 400,
  [ErrorCode.SUPPORT_TICKET_DESCRIPTION_REQUIRED]: 400,
  [ErrorCode.EMERGENCY_CONTACT_NOT_AUTHORIZED]: 403,
  [ErrorCode.EMERGENCY_CONTACT_ALREADY_EXISTS]: 409,
  [ErrorCode.EMERGENCY_CONTACT_INVALID_MOBILE]: 400,
  [ErrorCode.EMERGENCY_CONTACT_NAME_REQUIRED]: 400,
  [ErrorCode.REFERRAL_CODE_INVALID]: 400,
  [ErrorCode.REFERRAL_CODE_EXPIRED]: 400,
  [ErrorCode.REFERRAL_CODE_ALREADY_USED]: 400,
  [ErrorCode.REFERRAL_NOT_ELIGIBLE]: 400,
  [ErrorCode.KYC_DOCUMENT_MISSING]: 400,
  [ErrorCode.KYC_DOCUMENT_INVALID]: 400,
  [ErrorCode.KYC_AADHAR_INVALID]: 400,
  [ErrorCode.KYC_PAN_INVALID]: 400,
  [ErrorCode.KYC_LICENSE_INVALID]: 400,
  [ErrorCode.KYC_LICENSE_EXPIRED]: 400,
  [ErrorCode.KYC_IFSC_INVALID]: 400,
  [ErrorCode.KYC_BANK_DETAILS_INCOMPLETE]: 400,
  [ErrorCode.KYC_SELFIE_REQUIRED]: 400,
  [ErrorCode.KYC_ALREADY_SUBMITTED]: 400,
  [ErrorCode.ADMIN_ONLY]: 403,
  [ErrorCode.ADMIN_USER_NOT_FOUND]: 404,
  [ErrorCode.ADMIN_INVALID_ACTION]: 400,
  [ErrorCode.ADMIN_KYC_ALREADY_PROCESSED]: 400,
  [ErrorCode.ADMIN_INVALID_STATUS]: 400,
  [ErrorCode.ADMIN_INVALID_SETTINGS]: 400,
  [ErrorCode.EARNINGS_INSUFFICIENT_BALANCE]: 400,
  [ErrorCode.EARNINGS_PAYOUT_PENDING]: 400,
  [ErrorCode.EARNINGS_PAYOUT_FAILED]: 500,
  [ErrorCode.EARNINGS_INVALID_AMOUNT]: 400,
  [ErrorCode.EARNINGS_BANK_DETAILS_REQUIRED]: 400,

  // Payment errors
  [ErrorCode.PAYMENT_INVALID_AMOUNT]: 400,
  [ErrorCode.PAYMENT_INVALID_TRANSACTION]: 400,
  [ErrorCode.PAYMENT_ALREADY_PROCESSED]: 400,
  [ErrorCode.PAYMENT_FAILED]: 400,
  [ErrorCode.PAYMENT_CANCELLED]: 400,
  [ErrorCode.PAYMENT_INVALID_HASH]: 400,
  [ErrorCode.PAYMENT_GATEWAY_ERROR]: 502,
  [ErrorCode.PAYMENT_INSUFFICIENT_BALANCE]: 400,
  [ErrorCode.PAYMENT_REFUND_FAILED]: 500,
  [ErrorCode.PAYMENT_METHOD_INVALID]: 400,
  [ErrorCode.PAYMENT_TIMEOUT]: 408,
  [ErrorCode.PAYMENT_DECLINED]: 400,
  [ErrorCode.WALLET_INSUFFICIENT_BALANCE]: 400,
  [ErrorCode.WALLET_INVALID_AMOUNT]: 400,
  [ErrorCode.WALLET_TRANSACTION_EXPIRED]: 400,
  [ErrorCode.WALLET_TRANSACTION_INVALID]: 400,
  [ErrorCode.WALLET_MINIMUM_BALANCE]: 400,

  // Upload errors
  [ErrorCode.UPLOAD_FILE_REQUIRED]: 400,
  [ErrorCode.UPLOAD_FILE_TOO_LARGE]: 400,
  [ErrorCode.UPLOAD_INVALID_FILE_TYPE]: 400,
  [ErrorCode.UPLOAD_FAILED]: 500,
  [ErrorCode.UPLOAD_S3_ERROR]: 500,
  [ErrorCode.UPLOAD_AWS_CREDENTIALS_MISSING]: 500,
  [ErrorCode.UPLOAD_BASE64_INVALID]: 400,
  [ErrorCode.UPLOAD_STORAGE_QUOTA_EXCEEDED]: 413,
  [ErrorCode.UPLOAD_FILE_CORRUPTED]: 400,

  // External service errors
  [ErrorCode.EXTERNAL_SERVICE_UNAVAILABLE]: 503,
  [ErrorCode.EXTERNAL_SERVICE_TIMEOUT]: 504,
  [ErrorCode.EXTERNAL_SERVICE_ERROR]: 502,
  [ErrorCode.SMS_SERVICE_ERROR]: 502,
  [ErrorCode.EMAIL_SERVICE_ERROR]: 502,
  [ErrorCode.PAYMENT_GATEWAY_UNAVAILABLE]: 503,
  [ErrorCode.MAP_SERVICE_ERROR]: 502,
  [ErrorCode.NOTIFICATION_SERVICE_ERROR]: 502,

  // Rate limiting
  [ErrorCode.RATE_LIMIT_EXCEEDED]: 429,
  [ErrorCode.QUOTA_EXCEEDED]: 429,
  [ErrorCode.TOO_MANY_REQUESTS]: 429,
  [ErrorCode.DAILY_LIMIT_EXCEEDED]: 429,
  [ErrorCode.HOURLY_LIMIT_EXCEEDED]: 429,

  // Configuration errors
  [ErrorCode.CONFIG_MISSING]: 500,
  [ErrorCode.CONFIG_INVALID]: 500,
  [ErrorCode.FEATURE_DISABLED]: 503,
  [ErrorCode.MAINTENANCE_MODE]: 503,

  // Internal server errors
  [ErrorCode.INTERNAL_SERVER_ERROR]: 500,
  [ErrorCode.DATABASE_ERROR]: 500,
  [ErrorCode.DATABASE_CONNECTION_ERROR]: 500,
  [ErrorCode.DATABASE_QUERY_ERROR]: 500,
  [ErrorCode.DATABASE_TRANSACTION_ERROR]: 500,
  [ErrorCode.CACHE_ERROR]: 500,
  [ErrorCode.NOT_IMPLEMENTED]: 501,
  [ErrorCode.SERVICE_UNAVAILABLE]: 503,
  [ErrorCode.UNKNOWN_ERROR]: 500,
};

/**
 * Get HTTP status code for error code
 */
export const getErrorStatus = (errorCode: ErrorCode): number => {
  return ErrorStatusMap[errorCode] || 500;
};

/**
 * Get error code category name
 */
export const getErrorCategory = (errorCode: ErrorCode): string => {
  if (errorCode >= 1000 && errorCode < 2000) return 'Authentication';
  if (errorCode >= 2000 && errorCode < 3000) return 'Validation';
  if (errorCode >= 3000 && errorCode < 4000) return 'Not Found';
  if (errorCode >= 4000 && errorCode < 5000) return 'Business Logic';
  if (errorCode >= 5000 && errorCode < 6000) return 'Payment';
  if (errorCode >= 6000 && errorCode < 7000) return 'Upload';
  if (errorCode >= 7000 && errorCode < 8000) return 'Rate Limit';
  if (errorCode >= 8000 && errorCode < 9000) return 'Configuration';
  if (errorCode >= 9000) return 'Server Error';
  return 'Unknown';
};
